dist: xenial
language: python
branches:
  only:
    - master
python: 3.6.4
install:
  - pip install -r requirements_dev.txt
  - pip install -e .
script:
  - pytest --cov=decorpy
after_success:
  - coveralls
